### ISSUE TITLE
Not extending the whole way up

### ISSUE THREAD

**Issue by peterbe** [derrickpelletier/react-loading-overlay#33]
I know my way around `float:left` but that's about it. I'm using your wonderful library on https://workon.app and one thing I've noticed is that it doesn't extend all the way up. See:

<img width="2060" alt="Screen Shot 2019-03-18 at 10 01 01 AM" src="https://user-images.githubusercontent.com/26739/54535559-230ba100-4965-11e9-8153-8fbb6ff43fd6.png">

I clicked around with the Inspector to see if anything had a padding or margin but they all say 0px. 

What I did find, but can't explain, is that if I "remove" the `position:relative` on the overlay wrapper, the overlay extends all the way. See:

<img width="2060" alt="Screen Shot 2019-03-18 at 10 01 05 AM" src="https://user-images.githubusercontent.com/26739/54535686-6cf48700-4965-11e9-960b-1a29bdd173a4.png">

Is it a bug? Or is it a problem with Bulma? Or something in this lib's instructions that I couldn't find?

**Comment by derrickpelletier** [comment]
Hi @peterbe 
I'm looking at the link you provided and it looks like it's working fine now?

**Comment by peterbe** [comment]
> it's working fine now?

Because I fixed it like this: https://github.com/peterbe/workon/blob/38a2d06597a53598229b03ac285bbc5ad1ee5676/src/App.css#L188-L194 :)

**Comment by derrickpelletier** [comment]
I think it's just a contextual bug. The styles are fully override-able for this reason! Because it relies on the styling of the parent all cases can't really be accommodate in one set of styles.

There's a whole section here on customizing if you need alternative to the one you came up with
https://github.com/derrickpelletier/react-loading-overlay#custom-styling-nail_care
